name: pxt-buildtarget

on: [release]
  types: [published]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install target
        run: |
          sudo apt-get install xvfb
          sudo npm install -g pxt
          sudo npm install -g gulp
          npm install
      - name: npm install electron wrapper
        run: |
          git clone microsoft/pxt-electron
          git clone microsoft/pxt-deployment-config
          cd pxt-electron
          npm install
      - name: package electron build
        run: gulp package -t .. --internalelectron --crowdintoken $CROWDIN_KEY --product ../pxt-deployment-config/electron/arcade/product.json --typings ../node_modules/pxt-core/localtypings
      - name: extract electron installer
        run: |
          gulp installer-only -target ..
          gulp extract-execution-stub
          gulp clean-installer
          gulp set-squirrel-icon --target ..
      - name: upload app
        run: gulp upload-to-release --repo $PXT_RELEASE_REPO

        env:
          CROWDIN_KEY: ${{ secrets.CROWDIN_KEY }}
          PXT_ACCESS_TOKEN: ${{ secrets.PXT_ACCESS_TOKEN }}
          PXT_RELEASE_REPO: ${{ secrets.PXT_RELEASE_REPO }}
          PXT_ELECTRON_BUILD: ${{ secrets.PXT_ELECTRON_BUILD }}
          CHROME_BIN: chromium-browser
          DISPLAY: :99.0
          CI: true